### ISSUE TITLE
qvhighlights/umt_base_pretrain_100e_asr.py

### ISSUE THREAD

**Issue by c1d2y3** [TencentARC/UMT#46]
运行launch.py configs/qvhighlights/umt_base_pretrain_100e_asr.py的时候报错。
Traceback (most recent call last):
  File "E:\SF5\UMT-main\tools\launch.py", line 67, in <module>
    main()
  File "E:\SF5\UMT-main\tools\launch.py", line 63, in main
    engine.launch(eval=args.eval)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\engine\engine.py", line 529, in launch
    self.run_stage()
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\engine\engine.py", line 468, in run_stage
    self.train_epoch()
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\engine\engine.py", line 408, in train_epoch
    for data in self.data_loader:
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\parallel\collate.py", line 69, in collate
    return {
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\parallel\collate.py", line 70, in <dictcomp>
    k: collate([d[k] for d in batch], samples_per_gpu)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\nncore\parallel\collate.py", line 52, in collate
    stacked.append(default_collate(padded))
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\utils\data\_utils\collate.py", line 136, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\storage.py", line 487, in _new_shared
    untyped_storage = module._UntypedStorage._new_shared(size * cls().element_size())
  File "D:\ProgramData\Anaconda3\envs\MUT\lib\site-packages\torch\storage.py", line 172, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <0000020412B6EEA2>, error code: <1455>

**Comment by yeliudev** [comment]
Please double-check your environment settings and make sure they are the same as ours in README.
